services:

  db:
    image: postgres:17
    restart: always
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
      - POSTGRES_DB=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U n8n -d n8n']
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    restart: always
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5678:5678"
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files

  n8n-worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: worker
    env_file:
      - .env
    depends_on:
      - db
      - redis
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files
  
  # n8n-runners:
  #   image: n8nio/runners:1.111.0
  #   container_name: n8n-runners
  #   environment:
  #     - N8N_RUNNERS_TASK_BROKER_URI=http://n8n-main:5679
  #     - N8N_RUNNERS_AUTH_TOKEN=your-secret-here
  #     # etc.
  #   depends_on:
  #     - n8n

volumes:
  n8n_data:
  postgres_data:
  redis_data: