services:

  db:
    image: postgres:17
    environment:
      - POSTGRES_USER=n8n
      - POSTGRES_PASSWORD=n8n
      - POSTGRES_DB=n8n
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -h localhost -U n8n -d n8n']
      interval: 5s
      timeout: 5s
      retries: 10

  redis:
    image: redis:7-alpine
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', '--raw', 'incr', 'ping']
      interval: 5s
      timeout: 5s
      retries: 10

  n8n:
    build:
      context: .
      dockerfile: Dockerfile
    image: n8n_server
    command: start
    ports:
      - "5678:5678"
    env_file:
      - .env
    depends_on:
      - redis
      - db
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files

  n8n-worker:
    build:
      context: .
      dockerfile: Dockerfile
    image: n8n_server
    command: worker
    environment:
      - N8N_WORKERS_ENABLED=true
    env_file:
      - .env
    depends_on:
      - redis
    volumes:
      - n8n_data:/home/node/.n8n
      - ./local-files:/files

volumes:
  n8n_data:
  redis_data:
  postgres_data: